import random
class movieSeats:
  def show1Seats():
    seat1 = random.randint(1,30)
    print(' ')
    print(seat1)
    seat2 = random.randint(1,30)
    print(' ')
    print(seat2)
    seat3 = random.randint(1,30)
    print(' ')
    print(seat3)
    seat4 = random.randint(1,30)
    print(' ')
    print(seat4)
    seat5 = random.randint(1,30)
    print(' ')
    print(seat5)
    seat6 = random.randint(1,30)
    print(' ')
    print(seat6)
    seat7 = random.randint(1,30)
    print(' ')
    print(seat7)
    seat8 = random.randint(10,11)
    print(' ')
    print(seat8)
    seat9 = random.randint(14,19)
    print(' ')
    print(seat9)
    seat10 = random.randint(26,30)
    print(' ')
    print(seat10)
    seat11 = random.randint(21,23)
    print(' ')
    print(seat11)
    seat12 = random.randint(6,8)
    print(' ')
    print(seat12)
    seat13 = random.randint(11,13)
    print(' ')
    print(seat13)
    seat14 = random.randint(4,5)
    print(' ')
    print(seat14)
    seat15 = random.randint(1,3)
    print(' ')
    print(seat15)
    print('are taken please enter a number between 1 and 30 that are not taken')
    yourSeat = int(input(' your seat number goes here: '))
    while(True):
      if(yourSeat != seat1 and yourSeat != seat2 and yourSeat != seat3 and yourSeat != seat4 and yourSeat != seat5 and yourSeat != seat6 and yourSeat != seat7 and yourSeat != seat8 and yourSeat != seat9 and yourSeat != seat10 and yourSeat != seat11 and yourSeat != seat12 and yourSeat != seat13 and yourSeat != seat14 and yourSeat != seat15):
        print('success')
        break
      else:
        print('error')
        yourSeat = int(input("please enter a seat number that isn't taken : "))
  show1Seats()